---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] || 13 %>
  chef_license: accept

verifier:
  name: inspec

platforms:
  - name: debian-10

suites:
  - name: default
    run_list:
      - recipe[ragemp]
    attributes:
      ragemp:
        prefix: /opt
        version: "036"
        config:
          maxplayers: 10
          name: "RAGE:MP testing server"
          gamemode: mymod
          stream-distance: 100.0
          announce: false
          port: 22022
